(let ([x1 (read)])
(let ([x2 (read)])
(let ([x3 (read)])
(let ([x4 (read)])
(let ([x5 (read)])
(let ([x6 (read)])
(let ([x7 (read)])
(let ([x8 (read)])
(let ([x9 (read)])
(let ([x10 (read)])
(let ([x11 (read)])
(let ([x12 (read)])
(let ([x13 (read)])
(let ([x14 (read)])
(let ([x15 (read)])
(let ([x16 (read)])
  (+ (+ (+ (+ (+ x2 (- x1)) (+ x3 (- x4)))
	   (+ (+ x6 (- x5)) (+ x7 (- x8))))
	(+ (+ (+ x10 (- x9)) (+ x11 (- x12)))
	   (+ (+ x14 (- x13)) (+ x15 (- x16)))))
     42)))))))))))))))))
